name       : clojure-tools
version    : 1.10.3.1040
release    : 2
source     :
    - https://download.clojure.org/install/clojure-tools-1.10.3.1040.tar.gz : fb6d68deeb1bc5e3a869ceee98fcd968335589fcb57e31ee4ee8e034ab4d7977
license    : EPL-1.0
component  : programming.tools
summary    : Clojure tools launch a REPL manage libraries and start Clojure programs
description: |
    The Clojure command line tools can be used to start a Clojure repl, use Clojure and Java libraries, and start Clojure programs.
rundeps    :
    - openjdk-11
    - rlwrap
install    : |

    install -Dm00644 deps.edn $installdir/usr/lib/clojure/deps.edn
    install -Dm00644 example-deps.edn $installdir/usr/lib/clojure/example-deps.edn
    install -Dm00644 tools.edn $installdir/usr/lib/clojure/tools.edn
    install -Dm00644 exec.jar $installdir/usr/lib/clojure/libexec/exec.jar
    install -Dm00644 clojure-tools-$version.jar $installdir/usr/lib/clojure/libexec/clojure-tools-$version.jar

    sed -i -e 's@PREFIX@/usr/lib/clojure/@g' clojure
    sed -i -e 's@BINDIR@/usr/bin/@g' clj
    install -Dm00755 clojure $installdir/usr/bin/clojure
    install -Dm00755 clj $installdir/usr/bin/clj

    install -Dm00644 clojure.1 $installdir/usr/share/man/man1/clojure.1
    install -Dm00644 clj.1 $installdir/usr/share/man/man1/clj.1
